### PR TITLE
Use super for errors to propagate cause

### PR DESCRIPTION
**Pull request by FZambia**
Alternative solution for #55

### CODE REVIEW

**Comment by PhilipDukhov** [comment]
Actually, I don't know Java that deeply, mostly from how it interacts with kotlin=)

After discovering `super` looks much better than `initCause` 👍

**Comment by PhilipDukhov** [comment]
Also, if you decide to start from scratch, you can ask me for some suggestions and help with the API.

I'd do it in Kotlin, as it requires much less boilerplate - like you can use default parameters and no need to duplicate methods.

But even if you decide to stick with Java for your own reasons, there're some stuff I can help with.

e.g. in Java world builder pattern is often used, so you can build things like options inline, like 
```
new Client(
    endpoint, 
    Options.Builder()
		.setToken("")
		.build(), 
    listener
);
```
An other thing I'd change is updating `ResultCallback` to be safer - right now you can pass both exception and success result, which is ambiguous

**Comment by PhilipDukhov** [comment]
Yeah, you can even use `kotlin.Result` - it should work in Java, not sure how good is its API from Java side, but for kotlin lib users it'll be nice =)

**Comment by FZambia** [comment]
I guess it's a good thing, but adding types from Kotlin goes beyond my current understanding :) I'd prefer keeping things simple here, to avoid problems with maintaining. I just [opened a separate issue](https://github.com/centrifugal/centrifuge-java/issues/59) for keeping Result type in mind.

**Pull request merged**
