### PR TITLE
add SubscriptionOptions parameter to newSubscription

### LINKED ISSUE #52: How to subscribe to private channel in v2 API?
I'm using the latest version 0.2.5

I've found [`SubscriptionOptions`](https://github.com/centrifugal/centrifuge-java/blob/cd0c537b452e71f797e5e8d5a68a16aa56ae7c4c/centrifuge/src/main/java/io/github/centrifugal/centrifuge/SubscriptionOptions.java#L6) with `token` parameter which looks like what I need, but i don't see a way to pass it - [`newSubscription`](https://github.com/centrifugal/centrifuge-java/blob/cd0c537b452e71f797e5e8d5a68a16aa56ae7c4c/centrifuge/src/main/java/io/github/centrifugal/centrifuge/Client.java#L524) doesn't accept any related parameters and there's no other way to create a subscription.

### PR DESCRIPTION
**Pull request by PhilipDukhov**
Allows authenticating for private channels. Fixes #52

### CODE REVIEW

**Comment by FZambia** [comment]
@PhilipDukhov many thanks! That's an unfortunate miss..

Could you please put options before listener in the constructor? To match order of arguments in a Client constructor.

**Comment by PhilipDukhov** [comment]
@FZambia sure, done 👍

**Comment by PhilipDukhov** [comment]
Passed the checks

**Comment by FZambia** [comment]
Since we keep the old API here, then what is it better in your opinion:

1. Match Client constructor and have SubscriptionOptions a second argument in new API?
2. Or, have SubscriptionOptions a third argument in new API (after listener, like in your original PR version)?

For me 2 since more natural, but what do you think?

**Comment by PhilipDukhov** [comment]
I'd prefer using same style in whole project, so I'd prefer 1.

Also even if we could make breaking changes, I think options on the second place still looks more natural - if you create listener on place, it's easier to read with listener as the last argument, e.g.
```
client.newSubscription(
        "chat:index",
        new SubscriptionOptions(),
        new SubscriptionEventListener() {
            @Override
            public void onSubscribing(Subscription sub, SubscribingEvent event) {
                MainActivity.this.runOnUiThread(() -> tv.setText(String.format("Subscribing to %s, reason: %s", sub.getChannel(), event.getReason())));
            }
        }
);
```

**Pull request merged**
