### PR TITLE
remove subscription from map on unsubscribe

### PR DESCRIPTION
**Pull request by DenisKleshchev**
Subscriptions are not removed from `subs` map when unsubscribe from them

### CODE REVIEW

**Comment by FZambia** [comment]
Hello, unsubscribe operation should not remove subscription from map, it should only move subscription to `unsubscribed` state. Is there any problem you are trying to solve?

**Comment by DenisKleshchev** [comment]
There is no way to re-subscribe to a channel. For example, user enters some chat from the chat list, then returns back to the list end enters again to the same chat. I try to subscribe to this channel and get `DuplicateSubscriptionException` because map `subs` already contains item for this channel. Is there way to reuse a subscription?

**Comment by FZambia** [comment]
You can reuse the same subscription and call its `subscribe` [method](https://github.com/centrifugal/centrifuge-java/blob/master/centrifuge/src/main/java/io/github/centrifugal/centrifuge/Subscription.java#L74)

**Comment by DenisKleshchev** [comment]
so should I keep all the subscriptions I ever made in some map and reuse them every time or is there any way to auto-handle it?

**Comment by FZambia** [comment]
Yeah, at moment the only way is to keep references to existing subscriptions. I suppose we can add some helper to get Subscription object from internal client map if it's already exists.

The reason why it's not a good idea to just remove Subscription from internal map is that it theoretically can contain recovery state you want to reuse on next subscribe. This is not implemented at moment but I suppose this is a logical step for future version.

**Comment by DenisKleshchev** [comment]
Maybe then replace

```if (this.subs.get(channel) != null) {
    throw new DuplicateSubscriptionException();
}```

with 

```if (this.subs.get(channel) != null) {
    this.subs.get(channel).subscribe();
}```

?

**Comment by FZambia** [comment]
This is not obvious in terms of `SubscriptionEventListener ` argument of `Subscribe` call. Should we replace it in existing Subscription if found it in map? Also it does not protect developer from mistakes when he tries to subscribe to some channel while Client already subscribed to it.

**Comment by FZambia** [comment]
I am still thinking that adding an extra helper method to check for existing Subscription is a safe way to extend current behavior.

One more possible option is overloaded `unsubscribe` method of Subscription that accepts `UnsubscribeOptions` as argument. Maybe you could just call:

```
sub.unsubscribe(UnsubscribeOptions.Builder().setForever(true).Build());
```

And this call will remove subscription from internal map.

What do you think?

**Comment by DenisKleshchev** [comment]
Yeah, now I got it. Reuse subscriptions may lead to call lost `SubscriptionEventListener` callbacks and user will not receive any event. So the only possible way is to overload `unsubscribe` method as you say

**Comment by DenisKleshchev** [comment]
I've implemented overloaded `unsubscribe` method with `UnsubscribeOptions` parameter and now it looks like I'm facing a new issue. If user calls `Client.disconnect()`, it ignores all options and turns all subscriptions in the map into `UNSUBSCRIBED` state and calls their listeners `onUnsubscribe()` callbacks. Looks like client must manage order of method calls - to call `Client.disconnect()` only after unsubscribing all the subscriptions.

I think the best workaround so far is to make `Client.getSub(String channel)` and `Subscription.getListener()` **public**, and then on client side check if the centrifuge client already has subscription for this channel and use it with existing listener, or create a new one.

What do you think?

**Comment by FZambia** [comment]
Hm, not sure I understand what you mean - maybe a simple code example will make it clear.

At least now client first calls `onUnsubscribe` callbacks and then calls `onDisconnect` - https://github.com/centrifugal/centrifuge-java/blob/master/centrifuge/src/main/java/io/github/centrifugal/centrifuge/Client.java#L229

Btw as soon as we start removing Subscription from `subs` map we also need to synchronize it with `Client.subscribe` method which checks existence of subscription in map and can be called from another thread.

**Comment by DenisKleshchev** [comment]
I'm working on android chat application using centrifuge. On start it connects to the client and subscribes to the user channel (not private one) and shows chat list. When user clicks on a chat, app subscribes to a private channel of this chat. What I want to do is:

- allow user to enter different chats one by one and several times to any one of them;
- if user is in chat list and turns off the screen, app should unsubscribe from user channel subscription and disconnect from the client;
- if user is in a chat and turns off the screen, app should unsubscribe from user channel and this chat channel subscriptions and disconnect from the client;
- on turning screen on app must restore it's state - connect to the client and subscribe to the same subscriptions - user channel and if it is in chat state to private chat channel.

For now there are three variants:

1. The library as-is. Does not allow me to do `client.subscribe(channelName, listener)` twice, it throws `DuplicateSubscriptionException`. Workaround for this variant is duplicate `subs` in app code and reuse subscriptions.
2. Replace throwing `DuplicateSubscriptionException` by returning existing subscription from the `subs` map. In this case everything seems to be ok, but I might loose access to SubscriptionEventListener of a subscription.
3. public `getSub` and `setListener` methods. In app code I check if `getSub(channelName)` is null. If it is, I call `client.subscribe(channelName, listener)` as usual, otherwise I call `getSub(channelName).setListener(newListener)` and `getSub(channelName).subscribe()`. In this case I somehow get _105 already subscribed_ error next after _onSubscribeSuccess_ callback call on private channels subscribe and _101 unauthorized_ error on user channel subscribe and right after then it connects successfully. Everything seems to work but I have some strange errors in log.

Maybe I do something ideology wrong? Which way is correct? I'm thinking of combining 2 and 3 scenario - reuse subscription in map with setting new listener to it. Or is it totally wrong?

**Comment by DenisKleshchev** [comment]
Ok, now I found that if I call `Client.connect()` it resubscribes to all `subs` automatically and it really solves half of my problems. The only one unsolved is repeated subscription - when app cals `Subscription.unsubscribe()` and then `Client.subscribe(theSameChannelName, listener)`. I suppose to take this solution:

```
Subscription cached = getSub(channel);
if (cached != null) {
    sub = cached;
    sub.setListener(listener);
} else {
    sub = new Subscription(Client.this, channel, listener);
    this.subs.put(channel, sub);
}
```

in `Client` plus 

```
void setListener(SubscriptionEventListener listener) {
    this.listener = listener;
}
```

in `Subscription`. Setting new listener is in `synchronized(subs)` block, so everything is going to be ok. I've tested it in my app and everything works fine. I'll close this request and create new one

**Pull request closed without merging**
