### PR TITLE
add possibility connection via proxy

### PR DESCRIPTION
**Pull request by fuliozor**

### CODE REVIEW

**Comment by FZambia** [comment]
@fuliozor hello, thanks! Could you provide some details about an issue this solves for you? Are you using a proxy in development or this is part of the production app?

**Comment by fuliozor** [comment]
@FZambia Hi! I develop corporate application and for connect to corporate services from outside we use proxy. We use proxy and for development and from production.

**Comment by FZambia** [comment]
Just released 0.0.8 - should become available on Maven during a day, thanks!

**Comment by fuliozor** [comment]
Thank you! Have a nice day!

**Pull request merged**
